apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: sesaquecruz/cicd-lab2-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80